commerce/auctions/urls.py
from django.urls import path

from . import views
app_name = "auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.createListing, name="create"),
    path("<int:id>/visit", views.visit,name="visit"),
    path("categories", views.categories, name="categories"),
    path("<str:category>/category_list",views.category_list, name="category_list"),
    path("watchlist",views.Watchlist,name="watchlist"),
    path("<int:id>/biding",views.biding,name="biding"),
     path("<int:id>/deactivate",views.deactivate,name="deactivate"),
     path("<int:id>/comment",views.comment,name="comment"),
     path("<int:id>/adding_to_watchlist",views.adding_to_watchlist,name="addtowatchlist"),
]

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

commerce/auctions/models.py
from platform import mac_ver
from tkinter import CASCADE
from unicodedata import category
from django.contrib.auth.models import AbstractUser
from django.db import models
# Importing it to use it in the date field.
from django.utils import timezone
class User(AbstractUser):
    pass
    def __str__(self):
        return f"{self.username}"
class Listing(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(
            blank=True,
            max_length= 200
    )
    category = models.CharField(default="other",
        blank=True,
       max_length=50)
    price = models.FloatField(blank=False)
    date = models.DateTimeField(default=timezone.now)
    image = models.CharField(blank = True, max_length=2000)
    active = models.BooleanField(default=True)
    creator = models.ForeignKey(
        User, 
        on_delete= models.CASCADE,
        related_name="creator"
    )
class Bid(models.Model):
    user = models.ForeignKey(
        User,
        on_delete= models.CASCADE,
        related_name="bider"
    )
    item = models.ForeignKey(
        Listing, 
        on_delete= models.CASCADE,
        related_name="list"
    )
    bid = models.IntegerField(default=0)
    numberofbids = models.IntegerField(default=0)
    # The purpose of this class is to define to the objects.latest function
    # That it work on the bid column
    class Meta:
        get_latest_by = 'bid'
class Comment(models.Model):
    user = models.ForeignKey(
        User,
        on_delete= models.CASCADE,
        related_name="commenter"
    )
    item = models.ForeignKey(
        Listing, 
        on_delete= models.CASCADE,
        related_name="commented_item"
    )
    comment = models.CharField(max_length=1000)
class watchlist(models.Model):
    user = models.ForeignKey(
        User,
        on_delete= models.CASCADE,
        related_name="watcher"
    )
    item = models.ForeignKey(
        Listing, 
        on_delete= models.CASCADE,
        related_name="watche_item"
    )
    watched = models.BooleanField(default=False)
    number_watch = models.IntegerField(default=0)

commerce/auctions/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,  login,  logout
from django.db import IntegrityError
from django.http import  HttpResponseRedirect
from django.shortcuts import  render
from django.shortcuts import render
from django.urls import reverse
from django import forms
from django.db import IntegrityError
from django.db.models import F
from .models import *



# A Form for Creating a new item in the auctions.
class CreateForm(forms.Form):
    cateogory_choices =[
        ('other', 'Other'), 
        ('watch', 'watch'), 
        ('cosmatics', 'cosmatics'), 
        ('electronics', 'Electronics'), 
        ('clothe', 'Clothe'), 
        ('sneakers', 'Sneakers'), 
        ('sport-gadget', 'Sport-Gadget'), 
        ('book', 'Book'), 
        ('painting', 'Painting'), 
        ('jewelry', 'jewelry')
    ]
    title = forms.CharField(label='', 
     widget=forms.TextInput(attrs={
        "placeholder":"Enter title", 
        "autocomplete":"off", "class":"form"}))
    image = forms.CharField(label='', required= False, 
         widget=forms.TextInput(attrs={
        "placeholder":"Place place the image url here", 
        "autocomplete":"off", "class":"form"}))
    price = forms.CharField(label='', 
     widget=forms.TextInput(attrs={
        "placeholder":"Enter Price", 
        "autocomplete":"off", "class":"form"}))
    description = forms.CharField(label='', required=False, 
     widget=forms.Textarea(attrs={
        "placeholder":"Enter description", 
        "autocomplete":"off", "class":"form"}))
    category = forms.CharField(label="", required= False, 
      widget = forms.Select(choices=cateogory_choices , attrs={
         
      }))
# A Form for the biding.
class PriceForm(forms.Form):
        biding_price = forms.CharField(label='', 
        widget=forms.TextInput(attrs={
            "placeholder":"Enter your bid.", 
            "autocomplete":"off"}))
class commentForm(forms.Form):
    comment = forms.CharField(label='', 
        widget=forms.TextInput(attrs={
            "placeholder":"Comment", "autocomplete":"off", 
            "class":"comment"
        }
        ))

def index(request):
    # Retriving all the items from the database.
    active = Listing.objects.all()
    # Checking if the user is logged in
    # So we can count the number of items on his watchlist.
    if request.user.is_authenticated:
        # This query for the number of watched item by the user.
        watchers = watchlist.objects.filter(user = request.user, watched=True).count()
        return render(request,  "auctions/index.html", {'lists':active, 'watchers':watchers})
    else:
        return render(request,  "auctions/index.html", {'lists':active})

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request,  username=username,  password=password)

        # Check if authentication successful
        if user is not None: 
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request,  "auctions/login.html",  {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request,  "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request,  "auctions/register.html",  {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username,  email,  password)
            user.save()
        except IntegrityError:
            return render(request,  "auctions/register.html",  {
                "message": "Username already taken."
            })
        login(request,  user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request,  "auctions/register.html")
def createListing(request):
    # If the method is get then I will show the creation form.
    if request.method == "GET":
        watchers = watchlist.objects.filter(user = request.user, watched=True).count()
        return render(request,  "auctions/create.html", {'watchers':watchers, 
                         'form':CreateForm()
                 })
   # Otherwise it means the user have submited the form.
   # So I will check if it's valid or not.
   # Then I will add it to the database.
    form = CreateForm(request.POST or None)
    if request.method == "POST" and form.is_valid:
            title = request.POST['title']
            image = request.POST['image']
            price =request.POST['price']
            description = request.POST['description']
            category = request.POST['category']
            entry = Listing(title = title,  description = description,  category = category,  
                price = float(price),  image = image,  active = True, creator = request.user)
            entry.save()
            bid = Bid(user = request.user,  item = entry)
            bid.save()
           
            
            return HttpResponseRedirect(reverse("auctions:index"))
def visit(request,  id):
    if request.method == "GET":
        # Checking if the user is loged in or not...
        # To retrive the number of watched item if he is loged in. 
        # Otherwise I will not excute this query.
        if request.user.is_authenticated:
            detail = details(request,id,False,False,True)
        else:
            detail = details(request,id,False,False,False)

        return render(request, "auctions/entry.html", detail)
def deactivate(request, id):
    if request.method == "POST":
        # Changing the object status into unactive
        Listing.objects.filter(id = id).update(active = False)
        return HttpResponseRedirect(reverse("auctions:index"))
def categories(request):
    if request.method == "GET":
        # Counting the number of the watched element
        watchers = watchlist.objects.filter(user = request.user, watched=True).count()
        # Creating a dictionary which contains all the categories.
        infos= {"infos":["watch", "painting", "book", "clothe", "sneakers", "electronics", "cosmatics", "jewelry", 
            "sport-gadget", "other"], "watchers":watchers}
        return render(request, "auctions/category.html", infos)
def category_list(request, category):
    if request.method == "GET":
        # Retriving all the element in this category
        categoriesList = Listing.objects.filter(category = category)
        categorynumber = Listing.objects.filter(category = category).count()
        watchers = watchlist.objects.filter(user = request.user, watched=True).count()
        return render(request, "auctions/categories.html", {'lists':categoriesList, 
        'watchers':watchers,'category':category,
        'categorynumber':categorynumber})
            
        

@login_required
def comment(request, id):
    form = commentForm(request.POST or None)
    if request.method == "POST" and form.is_valid:
        # Taking the submitied comment from the user.
        com = request.POST["comment"]
        # Adding the comment to the comment table saving the user,  the item and th comment.
        save = Comment(user = request.user,  item_id = id,  comment = com)
        save.save()
    # Then I redriect to the visit page.
    return HttpResponseRedirect(reverse("auctions:visit", kwargs={'id':id}))
@login_required
def adding_to_watchlist(request, id):
    if request.method =="POST":
        set = watchlist.objects.filter(user = request.user, item_id = id).values()
        # Checking whtether the item the user intereacted with it before.
        if set.exists():
           # number  = watchlist.objects.filter(user = request.user, item_id = id).count().
           # here I just reverse it's status.
            if set[0]['watched']:
                watchlist.objects.filter(user = request.user, item_id = id).update(watched = False)
            else: 
        
                watchlist.objects.filter(user = request.user, item_id = id).update(watched = True)
        # if it was never on the watchlist then the I will add it and make it assigned as watched
        else:
            watch = watchlist(user =request.user,  item_id = id,  watched = True)
            watch.save()
        return HttpResponseRedirect(reverse("auctions:visit", kwargs={'id':id}))
@login_required
def biding(request,  id):
    form = PriceForm(request.POST or None)
    detail = {}
    if request.method == "POST" and form.is_valid:
        new_price = request.POST["biding_price"]
        listing = Listing.objects.get(id = id)
        
        old_price =listing.price
        if float(new_price) > old_price:
            Listing.objects.filter(id = id).update(price = new_price)
            bider = Bid.objects.filter(user = request.user,item_id = id).values()
            if bider.exists():
                    Bid.objects.filter(user = request.user,item_id = id).update(bid=new_price)
                    Bid.objects.filter(user = request.user,item_id = id).update(numberofbids = F('numberofbids')+1)
            else:
                 newbider = Bid(user = request.user,  item_id = id,bid = new_price,numberofbids =1)
                 newbider.save()
            detail = details(request,id,False,True,True)
       
        else:
           detail = details(request,id,True,False,True)
    return render(request, "auctions/entry.html", detail)
@login_required

commerce/auctions/templates/auctions/Watchlist.html
{% extends "auctions/layout.html" %}
{% block body %}
{% for watch in Watched%}
    <form action="{% url 'auctions:visit' watch.item.id %}" method="GET" >
        {% csrf_token %}
        <button type="sumbit" class = "btn btn-link" >{{watch.item.title}}</button>
    </form>
{%endfor%}














{% endblock %}

commerce/auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}
{% block body %}
<h1>{{category|capfirst}} Listings</h1>
{% if lists%}
    {% for list in lists %}
            {% if list.active %}
            <div class="lists">
            
                <div class ="image-border">
                    {% if list.image %}
                    <form action="{% url 'auctions:visit' list.id %}" method="get" >
                    {% csrf_token %}
                    <input type = "image" src = "{{ list.image}}" atl = "{{ list.title }}" class = "image_index"></input>
                    </form>
                    
                    {% else %}
                    <form action = "{% url 'auctions:visit' list.id %}" method="get" >
                    {% csrf_token %}
                    <input type = "image" src = 'https://www.ncenet.com/wp-content/uploads/2020/04/no-image-png-2.png' atl = "{{ list.title }}" class="image_index"></input>
                    </form>
                
                    {% endif %}
            </div>
                <div>
                <p class="head"><h4><strong>{{list.title}}</strong></h4></p>
                    <p><strong>Price: </strong>{{list.price}}$</p> 
                    <p>{{list.description }}</p>
                    <p id="date">Created {{list.date}}</p>
                
                </div>
     </div>
     <br>
        {%elif categorynumber == 1 %}
                <div class = "alert alert-primary" role = "alert">
                    No active lists available.
                </div>
        {%endif%}
    {% endfor %}
{% else%}
<div class = "alert alert-primary" role = "alert">
    No lists available yet.
  </div>
  {% endif %}

{% endblock %}

commerce/auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="container">
    {% for info in infos %}
    <div>
        <form action="{% url 'auctions:category_list' info %}" method ="get">
            {% csrf_token %}
            <input type="submit" value = "{{info}}" id="categories">
        </form>
    </div>
    {% endfor%}
</div>

{% endblock%}

commerce/auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}
{% block body %}
    <h2>Add New Entry</h2>
    <div class="Entry">
        <form action="{% url 'auctions:create' %}" method ="post">
            {% csrf_token %}
            
                {% for field in form  %}
                <div >
                    <b>{{ field.label_tag }}</b><br>  {{ field }} <br>
                 
                {% endfor %}
              
            <input type = "submit" value="Create" class ="bid">
          </div>
    </div>

    </form>
{% endblock %}

commerce/auctions/templates/auctions/entry.html
{% extends "auctions/layout.html" %}

{% block body %}
<div>
    {% if less %}
        <div class="alert alert-danger" role="alert">
            Please enter a higher bid.
        </div>
    {%endif%}
    {% if more %}
    <div class="alert alert-success" role="alert">
        You are the highest bider.  
    </div>
    {% endif %}
    <br>
    <h1>
        <strong>Listing:{{list.title}}</strong>
    </h1>
    <p>
    {% if user.is_authenticated %}
    <form action="{% url 'auctions:addtowatchlist' list.id %}" method ="post">
        {% csrf_token %}
        <input type="submit"  value ="Watchlist" id="watchlist">
    </form>
    </p>
    {% endif %}
</div>
<div>
{% if list.image%}
    <img src = "{{ list.image}} " atl = "{{ list.title }}"  class="image_index" >
  {% else %}
  <img src = 'https://www.ncenet.com/wp-content/uploads/2020/04/no-image-png-2.png' atl = "{{ list.title }}" width='450' height="350" p>
  {% endif %}
</div>
<div>
    <p class="title"><strong>{{list.title}}</strong></p>
    <p class="price">{{list.price}}$</p>
    {% if user.is_authenticated %}
        <p>({{numberofbids }}) bids have placed.</p>

    {% if list.active %}

            <form action="{% url 'auctions:biding' list.id %}" method ="post">
                {% csrf_token %}
                {{form}}<br>
                <input type="submit"  value ="Place a bid" class="bid">
            </form>
            {% if request.user == list.creator%}
            <form action="{% url 'auctions:deactivate' list.id %}" method ="post">
                {% csrf_token %}
                <input type="submit"  value ="Close auction" class="auction">
            </form>
            {% endif %}
    {%else%}

                {% if bid.user == request.user%}
                    <div class="alert alert-success" role="alert">
                        You won the auction.  
                    </div>
    
                {% else %}
                    <div class="alert alert-danger" role="alert">
                        You lost the auction.  
                    </div>
                {% endif %}
        {% endif %}
    {% endif %}
</div>
<div>
    <p><h1>Details</h1></p>
    <ul>
        <li><strong>Listed By:</strong><mark class="user">{{list.creator}}</mark></li>
        <li><strong>Category:</strong> {{list.category}}</li>
        {% if list.description %}
        <li><strong>Description:</strong> {{list.description}}</li>
        {% endif %}
    </ul>
</div>
{% if user.is_authenticated %}
    <div>
        <p><h1>Comments</h1></p>
        {% if comments %}
            {% for commen in comments%}
            <div class="comments">
            <strong>{{commen.user}} </strong>  | {{commen.comment}}
            </div>
            {% endfor %}
        {% else %}
            <h5>
                Be The first one to comment.
            </h5>
        {% endif %}
        <form action="{% url 'auctions:comment' list.id %}" method ="post">
            {% csrf_token %}
            {{comment}}
            <input type="submit"  value ="comment" class="bid">
        </form>

    </div>
{% endif %}
{% endblock %}

commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
<h1>Active Listings</h1>

{% for list in lists %}
  {% if list.active %}
 <div class="lists">
   
    <div class ="image-border">
        {% if list.image %}
        <form action="{% url 'auctions:visit' list.id %}" method="get" >
          {% csrf_token %}
          <input type="image" src="{{ list.image}}" atl = "{{ list.title }}" class="image_index"></input>
        </form>
          
        {% else %}
        <form action="{% url 'auctions:visit' list.id %}" method="get" >
          {% csrf_token %}
          <input type ="image" src = 'https://www.ncenet.com/wp-content/uploads/2020/04/no-image-png-2.png' atl = "{{ list.title }}" class="image_index"></input>
        </form>
      
        {% endif %}
  </div>
    <div>
      <p class="head"><h4><strong>{{list.title}}</strong></h4></p>
        <p><strong>Price: </strong>{{list.price}}$</p> 
        <p>{{list.description }}</p>
        <p id="date">Created {{list.date}}</p>
    
    </div>
    {% endif %}
 </div>
 <br>
{% endfor %}

  
{% endblock %}

commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        {% load static %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        {% load static %}
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet" type="text/css" media="screen">
    
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class = "nav-item">
                    <a class = "nav-link" href = "{% url 'auctions:categories'%}">Categories</a>
                </li>
                <li class = "nav-item">
                    <a class = "nav-link" href = "{% url 'auctions:watchlist' %}">Watctlist {{watchers}}</a>
                </li>
                <li class = "nav-itme">
                    <a class = "nav-link" href = "{% url 'auctions:create' %}">Create Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}